# Generated by Django 2.0.5 on 2018-06-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcar',
            name='user',
            field=models.ForeignKey(null=True, on_delete=2, to='App.UserInfo'),
        ),
        migrations.AlterField(
            model_name='shopcar',
            name='goods',
            field=models.ForeignKey(on_delete=1, to='App.Goods'),
        ),
    ]
