# Generated by Django 2.0.5 on 2018-06-26 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20180626_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcar',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Goods'),
        ),
    ]
