# Generated by Django 2.0.5 on 2018-06-26 13:23

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20180626_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcar',
            name='goods',
            field=models.ForeignKey(on_delete=1, to='App.Goods'),
        ),
        migrations.AlterField(
            model_name='shopcar',
            name='user',
            field=models.ForeignKey(default=datetime.datetime(2018, 6, 26, 13, 23, 37, 623822, tzinfo=utc), on_delete=2, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
