# Generated by Django 2.0.5 on 2018-06-25 13:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_remove_shopcar_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_name',
            new_name='userName',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_pass',
            new_name='userPasswd',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='userAccount',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='userAddress',
            field=models.CharField(default=datetime.datetime(2018, 6, 25, 13, 48, 10, 572007, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='userImg',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='userPhone',
            field=models.CharField(default=datetime.datetime(2018, 6, 25, 13, 48, 41, 971007, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='userRank',
            field=models.IntegerField(default=datetime.datetime(2018, 6, 25, 13, 48, 54, 690007, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
